config/routes.rb
Rails.application.routes.draw do
  get 'bye/logout'

  get 'bye/close'

  get 'greetings/new'

  root 'greetings#hello'

end

app/models/list.rb
class List < ActiveRecord::Base
  @keychain = List.find(1)
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/bye_controller.rb
class ByeController < ApplicationController
  def logout
    @logout = {
      bye: "see you next time buddy!",
      angry: "hey get out of here men. really. OUT!"
    }
  end

  def close
  end
end

app/controllers/greetings_controller.rb
class GreetingsController < ApplicationController
  def hello
    @greetings
    @keychain = List.find(1)
  end

  def new
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/bye_helper.rb
module ByeHelper
end

app/helpers/greetings_helper.rb
module GreetingsHelper
end

app/views/bye/close.html.erb
<h1>Bye#close</h1>
<p>Find me in app/views/bye/close.html.erb</p>

app/views/bye/logout.html.erb
<h1>Bye#logout</h1>
<p>Find me in app/views/bye/logout.html.erb</p>


<% @logout.each_value do |value| %>
  <%= value %>
  <br>
<% end %>

<br>
<%= link_to "go to home", root_path %>

app/views/greetings/hello.html.erb
<div class="row">
  <div class="col-md-8">
    <h1>Greetings#hello</h1>
    <p>Find me in app/views/greetings/hello.html.erb</p>

    <%= @keychain.item %><br>
    <%= @keychain.amount %><br>
    <%= @keychain.desc %><br>

    <%= link_to "go to greetings", bye_logout_path %>
  </div>
  <div class="col-md-4">
    <h1> bootstrap working </h1>
  </div>
</div>

app/views/greetings/new.html.erb
<div class="row">
  <div class "col-md-12">
    <h1>Form</h1>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Rails27Jan</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
  <div class="container">
    <%= yield %>
  </div>
</body>
</html>